volumes:
    postgres-dat:
services:
  postgres:
    image: postgres:16
    shm_size: '1gb'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - 'postgres-dat:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
  backend:
    build:
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    restart: on-failure
    command: bash -c "alembic upgrade head && gunicorn app:app --config python:config.gunicorn"
    volumes:
      - './web:/app:z'
    ports:
      - "8080:8080"
    depends_on:
      - postgres
